name: lm
# conda env create -f requirements.yml
# then conda activate dl
# to remove, simply do conda env remove -n dl
channels:
- anaconda # default one
- pytorch # necessary for pytorch and torchvision
dependencies:
- python=3.8
- matplotlib=3.0.1
- nb_conda
- numpy=1.15.2
- pip # needed to install pip dependencies below
- pytorch
- torchvision
- scipy=1.1.0
- tensorboard
- pip:
  - scikit-learn==0.20.0
  - opencv-contrib-python==4.0.0.21
